
version: "3.2"

services:
  
  google-cloud-sdk:
    image: google/cloud-sdk:latest
    container_name: google-cloud-config

  gcloud:
    image: google/cloud-sdk:latest
    container_name: gcloud-config
    command: gcloud
    tty: true

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
    ports:
      - 9200:9200
      - 9300:9300

  notebook:
    image: jupyter/datascience-notebook
    build:
      context: ./notebook
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ./notebook
        target: /home/jovyan/work/userdata
